var source = "https://kurul.diyanet.gov.tr/tr/fetva/mekruh-vakitler-hangileridir-hangi-vakitlerde-kaza-ve-hangi/0193c42d-52b7-7186-d5b4-f1d3c950ad73"
var messages = {
 en: {
  live:'Live',preview:'Preview',returnNow:'Return to now',explore:'Explore today',loading:'Calculating the local sky…',unavailable:'Solar view unavailable',coordinatesNeeded:'Choose coordinates to see the Earth and sun. Your prayer timetable is still available below.',
  timetableUnavailable:'Prayer interval unavailable',tomorrow:'Tomorrow',timeline:'Prayer timeline',timelineHint:'Drag to explore · Click a prayer for its exact time',nextPrayer:'Next prayer',current:'Current interval',next:'Next transition',details:'Interval details',choose:'Select an interval',prayerRing:'Prayer timetable',solarRing:'Sun and twilight',guidanceRing:'Diyanet guidance',estimated:'Estimated',source:'Read the source',guidanceUnavailable:'Guidance timing unavailable: solar events or timetable boundaries are missing, or the estimated bands overlap.',
  daylight:'Daylight',civilTwilight:'Civil twilight',nauticalTwilight:'Nautical twilight',astronomicalTwilight:'Astronomical twilight',night:'Astronomical night',morning:'Morning',sunriseGuidance:'Sunrise kerâhet',noonGuidance:'Midday kerâhet',sunsetGuidance:'Sunset kerâhet',
  sunrise:'Calculated sunrise',sunset:'Calculated sunset',solarNoon:'Solar noon',altitude:'Sun elevation',azimuth:'Azimuth',rising:'Rising',setting:'Setting',above:'Above the horizon',below:'Below the horizon',
  assumptions:'Calculated for a level horizon and standard atmosphere. Terrain and weather can change the observed sunrise and sunset.',
  previewHint:'Preview changes the view only. Live reminders continue normally.',guidanceHint:'Diyanet guidance uses estimated boundaries. Prayer-specific exceptions apply; dismissing a reminder does not record a prayer.',
  continued:'Continues beyond this day',calculated:'Astronomical calculation',timetable:'Selected prayer timetable',
  explain_Fajr:'Fajr is due before sunrise. Diyanet restricts other voluntary prayers in this period, apart from the Fajr sunnah. This is not a blanket prohibition on prayer.',
  explain_morning:'The morning gap between timetable sunrise and Dhuhr is not an obligatory prayer interval. Check the separate estimated sunrise restriction band.',
  explain_Dhuhr:'Dhuhr runs from its selected timetable boundary until Asr. The separate solar-noon marker follows astronomy and can differ from the timetable.',
  explain_Asr:'Asr remains due before sunset. Diyanet advises against voluntary prayers after you have prayed Asr. The near-sunset restriction has an exception for that day’s obligatory Asr; delaying it without an excuse is discouraged.',
  explain_Maghrib:'Maghrib starts at the selected timetable time. Diyanet advises performing its obligatory prayer before voluntary prayers.',
  explain_Isha:'Isha begins at the selected timetable time. This band shows the timetable interval until the next Fajr, not a judgement that every part of it is equally preferable.',
  explain_daylight:'The sun has risen and has not yet set. These astronomical boundaries are independent of prayer-timetable adjustments.',
  explain_civilTwilight:'Twilight while the sun is within about 6° below the horizon. Its brighter end is the calculated sunrise or sunset.',
  explain_nauticalTwilight:'Twilight while the sun is between 6° and 12° below the horizon.',
  explain_astronomicalTwilight:'Twilight while the sun is between 12° and 18° below the horizon. These angles are not a substitute for your selected Fajr or Isha method.',
  explain_night:'The sun is more than 18° below the horizon. This describes astronomical darkness, not a separate prayer ruling.',
  explain_sunriseGuidance:'Estimate: calculated sunrise plus 45 minutes. Diyanet describes roughly 40–50 minutes in moderate regions. Its guidance restricts prayers during this period, with specific exceptions explained in the source.',
  explain_noonGuidance:'Estimate: the 10 minutes immediately before timetable Dhuhr. This is an approximate Diyanet guidance band around midday, not a claim that the sun is vertically overhead.',
  explain_sunsetGuidance:'Estimate: the 45 minutes before calculated sunset. Diyanet describes roughly 40–50 minutes in moderate regions. That day’s obligatory Asr is an exception; it should not deliberately be delayed to this period.'
 },
 tr: {
  live:'Canlı',preview:'Önizleme',returnNow:'Şimdiye dön',explore:'Bugünü keşfet',loading:'Yerel gökyüzü hesaplanıyor…',unavailable:'Güneş görünümü kullanılamıyor',coordinatesNeeded:'Dünya ve Güneş görünümü için koordinat seçin. Namaz çizelgeniz aşağıda kullanılabilir.',
  timetableUnavailable:'Namaz aralığı kullanılamıyor',tomorrow:'Yarın',timeline:'Namaz zaman çizgisi',timelineHint:'Keşfetmek için sürükleyin · Tam saati için namaza tıklayın',nextPrayer:'Sonraki namaz',current:'Şu anki aralık',next:'Sonraki geçiş',details:'Aralık ayrıntıları',choose:'Bir aralık seçin',prayerRing:'Namaz çizelgesi',solarRing:'Güneş ve alacakaranlık',guidanceRing:'Diyanet rehberi',estimated:'Yaklaşık',source:'Kaynağı oku',guidanceUnavailable:'Rehber zamanlaması kullanılamıyor: Güneş olayları veya namaz sınırları eksik ya da tahmini aralıklar çakışıyor.',
  daylight:'Gündüz',civilTwilight:'Sivil alacakaranlık',nauticalTwilight:'Deniz alacakaranlığı',astronomicalTwilight:'Astronomik alacakaranlık',night:'Astronomik gece',morning:'Kuşluk dönemi',sunriseGuidance:'Doğuş kerâheti',noonGuidance:'Öğle kerâheti',sunsetGuidance:'Batış kerâheti',
  sunrise:'Hesaplanan doğuş',sunset:'Hesaplanan batış',solarNoon:'Güneş öğlesi',altitude:'Güneş yüksekliği',azimuth:'Azimut',rising:'Yükseliyor',setting:'Alçalıyor',above:'Ufkun üstünde',below:'Ufkun altında',
  assumptions:'Düz ufuk ve standart atmosfer için hesaplanır. Arazi ve hava, gözlenen doğuş ve batışı değiştirebilir.',
  previewHint:'Önizleme yalnızca görünümü değiştirir. Canlı hatırlatmalar normal çalışır.',guidanceHint:'Diyanet rehberi yaklaşık sınırlara dayanır. Namaza göre istisnalar vardır; hatırlatmayı kapatmak namaz kılındığını kaydetmez.',
  continued:'Bu günün ötesinde devam eder',calculated:'Astronomik hesap',timetable:'Seçilen namaz çizelgesi',
  explain_Fajr:'Sabah namazı güneş doğmadan kılınır. Diyanet bu aralıkta sabah sünneti dışındaki nâfileleri kısıtlar. Bu, bütün namazları kapsayan bir yasak değildir.',
  explain_morning:'Çizelgedeki güneş doğuşuyla öğle arasındaki dönem, farz namaz vakti değildir. Ayrı gösterilen yaklaşık doğuş kerâheti aralığına bakın.',
  explain_Dhuhr:'Öğle, seçilen çizelgedeki başlangıcından ikindiye kadar sürer. Ayrı Güneş öğlesi işareti astronomiye dayanır ve çizelgeden farklı olabilir.',
  explain_Asr:'İkindi güneş batmadan kılınmalıdır. Diyanet, ikindi kılındıktan sonra nâfile kılınmasını uygun görmez. O günün ikindi farzı batış öncesi kerâhetten istisnadır; mazeretsiz olarak bu vakte geciktirmek mekruhtur.',
  explain_Maghrib:'Akşam seçilen çizelgedeki saatte başlar. Diyanet, nâfilelerden önce akşamın farzını kılmayı öğütler.',
  explain_Isha:'Yatsı seçilen çizelgedeki saatte başlar. Bu bant sonraki imsaka kadar çizelge aralığını gösterir; her kısmın aynı derecede tercih edildiği anlamına gelmez.',
  explain_daylight:'Güneş doğmuş ve henüz batmamıştır. Bu astronomik sınırlar namaz çizelgesi ayarlamalarından bağımsızdır.',
  explain_civilTwilight:'Güneşin ufkun yaklaşık 6° altına kadar bulunduğu alacakaranlık. Aydınlık ucu hesaplanan doğuş veya batıştır.',
  explain_nauticalTwilight:'Güneş ufkun 6°–12° altındayken oluşan alacakaranlık.',
  explain_astronomicalTwilight:'Güneş ufkun 12°–18° altındayken oluşan alacakaranlık. Bu açılar seçtiğiniz imsak veya yatsı yönteminin yerine geçmez.',
  explain_night:'Güneş ufkun 18° altındadır. Bu, astronomik karanlığı anlatır; ayrı bir namaz hükmü değildir.',
  explain_sunriseGuidance:'Tahmin: hesaplanan doğuştan sonraki 45 dakika. Diyanet mutedil bölgelerde yaklaşık 40–50 dakika belirtir. Kaynakta açıklanan özel istisnalarla bu dönemde namaz kısıtlanır.',
  explain_noonGuidance:'Tahmin: çizelgedeki öğleden hemen önceki 10 dakika. Öğle çevresinde yaklaşık bir Diyanet rehber aralığıdır; Güneşin tam dik olduğu iddiası değildir.',
  explain_sunsetGuidance:'Tahmin: hesaplanan batıştan önceki 45 dakika. Diyanet mutedil bölgelerde yaklaşık 40–50 dakika belirtir. O günün ikindi farzı istisnadır; bilerek bu vakte geciktirilmemelidir.'
 },
 ar: {
  live:'مباشر',preview:'معاينة',returnNow:'العودة إلى الآن',explore:'استكشف اليوم',loading:'جارٍ حساب السماء المحلية…',unavailable:'عرض الشمس غير متاح',coordinatesNeeded:'اختر الإحداثيات لعرض الأرض والشمس. جدول الصلاة متاح أدناه.',
  timetableUnavailable:'فترة الصلاة غير متاحة',tomorrow:'غداً',timeline:'الخط الزمني للصلاة',timelineHint:'اسحب للاستكشاف · انقر الصلاة لعرض وقتها الدقيق',nextPrayer:'الصلاة التالية',current:'الفترة الحالية',next:'الانتقال التالي',details:'تفاصيل الفترة',choose:'اختر فترة',prayerRing:'جدول الصلاة',solarRing:'الشمس والشفق',guidanceRing:'إرشادات ديانت',estimated:'تقريبي',source:'اقرأ المصدر',guidanceUnavailable:'توقيت الإرشادات غير متاح: أحداث شمسية أو حدود صلاة مفقودة، أو تداخل بين الفترات التقديرية.',
  daylight:'النهار',civilTwilight:'الشفق المدني',nauticalTwilight:'الشفق البحري',astronomicalTwilight:'الشفق الفلكي',night:'الليل الفلكي',morning:'فترة الصباح',sunriseGuidance:'كراهة الشروق',noonGuidance:'كراهة الظهيرة',sunsetGuidance:'كراهة الغروب',
  sunrise:'الشروق المحسوب',sunset:'الغروب المحسوب',solarNoon:'الظهر الشمسي',altitude:'ارتفاع الشمس',azimuth:'السمت',rising:'صاعدة',setting:'هابطة',above:'فوق الأفق',below:'تحت الأفق',
  assumptions:'الحساب لأفق مستوٍ وغلاف جوي معياري. قد تؤثر التضاريس والطقس في الشروق والغروب المشاهدين.',
  previewHint:'تغيّر المعاينة العرض فقط. تستمر التذكيرات المباشرة بصورة طبيعية.',guidanceHint:'تستخدم إرشادات ديانت حدوداً تقريبية. توجد استثناءات حسب نوع الصلاة؛ إغلاق التذكير لا يسجّل أداء الصلاة.',
  continued:'تستمر بعد هذا اليوم',calculated:'حساب فلكي',timetable:'جدول الصلاة المختار',
  explain_Fajr:'تؤدى صلاة الفجر قبل الشروق. تقيد ديانت النوافل الأخرى في هذه الفترة باستثناء سنة الفجر. هذا ليس منعاً شاملاً للصلاة.',
  explain_morning:'الفترة بين شروق الجدول والظهر ليست وقت صلاة مفروضة. راجع فترة كراهة الشروق التقديرية المنفصلة.',
  explain_Dhuhr:'يمتد الظهر من بدايته في الجدول المختار إلى العصر. علامة الظهر الشمسي مستقلة وقد تختلف عن الجدول.',
  explain_Asr:'يؤدى العصر قبل الغروب. توصي ديانت بعدم التنفل بعد أداء العصر. فرض عصر ذلك اليوم مستثنى من كراهة ما قبل الغروب، ويكره تأخيره إليها بلا عذر.',
  explain_Maghrib:'يبدأ المغرب في موعد الجدول المختار. توصي ديانت بأداء فرضه قبل النوافل.',
  explain_Isha:'تبدأ العشاء في موعد الجدول المختار. يمثل الشريط الفترة حتى الفجر التالي، ولا يعني تساوي أفضلية جميع أجزائها.',
  explain_daylight:'أشرقت الشمس ولم تغرب بعد. هذه الحدود الفلكية مستقلة عن تعديلات جدول الصلاة.',
  explain_civilTwilight:'الشفق حين تكون الشمس ضمن نحو 6 درجات تحت الأفق. حده المضيء هو الشروق أو الغروب المحسوب.',
  explain_nauticalTwilight:'الشفق حين تكون الشمس بين 6 و12 درجة تحت الأفق.',
  explain_astronomicalTwilight:'الشفق حين تكون الشمس بين 12 و18 درجة تحت الأفق. هذه الزوايا لا تحل محل طريقة الفجر أو العشاء المختارة.',
  explain_night:'الشمس أكثر من 18 درجة تحت الأفق. هذا وصف للظلام الفلكي وليس حكماً مستقلاً للصلاة.',
  explain_sunriseGuidance:'تقدير: 45 دقيقة بعد الشروق المحسوب. تذكر ديانت نحو 40–50 دقيقة في المناطق المعتدلة. تقيد الصلاة خلالها مع الاستثناءات المحددة في المصدر.',
  explain_noonGuidance:'تقدير: الدقائق العشر السابقة لظهر الجدول. فترة إرشادية تقريبية حول الظهيرة، ولا تعني أن الشمس عمودية فوق المكان.',
  explain_sunsetGuidance:'تقدير: الدقائق الخمس والأربعون السابقة للغروب المحسوب. تذكر ديانت نحو 40–50 دقيقة في المناطق المعتدلة. فرض عصر ذلك اليوم مستثنى، وينبغي عدم تعمد تأخيره إليها.'
 }
}
function text(key,language){return (messages[language]||messages.en)[key]||messages.en[key]||key}
