var names = {
  en: {Fajr: "Fajr", Sunrise: "Sunrise", Dhuhr: "Dhuhr", Asr: "Asr", Maghrib: "Maghrib", Isha: "Isha"},
  tr: {Fajr: "İmsak", Sunrise: "Güneş", Dhuhr: "Öğle", Asr: "İkindi", Maghrib: "Akşam", Isha: "Yatsı"},
  ar: {Fajr: "الفجر", Sunrise: "الشروق", Dhuhr: "الظهر", Asr: "العصر", Maghrib: "المغرب", Isha: "العشاء"}
}
function prayer(name, language) { return (names[language] || names.en)[name] || name }

var messages = {
  en: {next: "Next prayer", after: "Time for", before: "Coming up", settings: "Settings", today: "Today",
    countdownHint:"Saves immediately. Before prayer: time until prayer. After prayer: time left in the green reminder. Hidden after dismissal.", countdownWindow:"Show bar countdown", countdownBoth:"Before and after prayer", countdownBefore:"Before prayer only", countdownAfter:"After prayer only", reminderEnds:"Reminder ends in",
    qiblaUndefined:"A unique qibla bearing is unavailable at this location.",
    qibla:"Qibla direction",trueNorth:"clockwise from true north",northShort:"N",showQibla:"Show qibla on Earth",showQiblaHint:"Saves immediately. A subtle dashed guide ends at Makkah when visible; otherwise it fades at the horizon. North stays at the top.",qiblaUnavailable:"Direction unavailable. Save a location with coordinates to calculate it.",
    displayMode: "Panel view", earth: "Earth clock", classic: "Classic timetable", guidanceProfile: "Prayer guidance", diyanetGuidance: "Diyanet · estimated boundaries", guidanceOff: "Off",
    coordinates: "Saved coordinates", coordinatesHint: "Editing the city or country switches back to city-name lookup.",
    coordinatePermission: "Fetching sends these saved coordinates to AlAdhan for prayer times.",
    autoLocation: "Automatic location", autoLocationHint: "Saves immediately and refreshes prayer times. Approximate city from your network; switch off to use your saved manual location.",
    autoPermission: "Automatic mode uses wttr.in to estimate your city from your public IP, then sends the detected coordinates to AlAdhan for prayer times.",
    done: "Acknowledged", dismiss: "Dismiss reminder", setup: "Welcome to Salah", setupBody: "Choose your location and prayer calculation method to get started.",
    notifications: "Desktop notifications", sound: "Audio", motion: "Gentle animation", countdown: "Show countdown in the bar",
    city: "City", country: "Country", method: "Calculation method", school: "Asr calculation", language: "Language",
    save: "Save & fetch times", back: "Back", refresh: "Refresh", preview: "Preview reminders", stop: "Stop audio",
    beforeWindow: "Minutes before prayer", afterWindow: "Minutes after prayer", normal: "Between reminders",
    permission: "Fetching sends your chosen city and country to AlAdhan. Your weather location stays separate.",
    source: "AlAdhan calculation", local: "Local timetable", expired: "Today’s schedule is unavailable. Refresh or update your timetable.",
    hint: "Click the mosque to dismiss the current reminder. Right-click opens this panel; middle-click refreshes.",
    acknowledgeOpen: "Click also opens the panel", soundFile: "Audio file (absolute path)", filePath: "Timetable JSON file (absolute path)",
    provider: "Timetable source", importSave: "Save & load timetable", ring: "Yellow: before Fajr / Dhuhr\nRed: before Asr / Maghrib / Isha\nGreen: just started", previewLabel: "Preview — not a live prayer alert"},
  tr: {next: "Sonraki namaz", after: "Vakit girdi", before: "Vakit yaklaşıyor", settings: "Ayarlar", today: "Bugün",
    countdownHint:"Anında kaydedilir. Öncesinde namaza, sonrasında yeşil hatırlatmanın bitişine kalan süreyi gösterir. Hatırlatma kapatılınca gizlenir.", countdownWindow:"Çubukta geri sayım", countdownBoth:"Namaz öncesi ve sonrası", countdownBefore:"Yalnızca namaz öncesi", countdownAfter:"Yalnızca namaz sonrası", reminderEnds:"Hatırlatmanın bitmesine",
    qiblaUndefined:"Bu konumda tek bir kıble yönü belirlenemiyor.",
    qibla:"Kıble yönü",trueNorth:"gerçek kuzeyden saat yönünde",northShort:"K",showQibla:"Dünya üzerinde kıbleyi göster",showQiblaHint:"Anında kaydedilir. Hafif kesik çizgi görünürse Mekke’de biter; değilse ufukta kaybolur. Kuzey üstte kalır.",qiblaUnavailable:"Yön belirlenemiyor. Hesaplamak için koordinatlı bir konum kaydedin.",
    displayMode: "Panel görünümü", earth: "Dünya saati", classic: "Klasik çizelge", guidanceProfile: "Namaz rehberi", diyanetGuidance: "Diyanet · yaklaşık sınırlar", guidanceOff: "Kapalı",
    coordinates: "Kayıtlı koordinatlar", coordinatesHint: "Şehir veya ülkeyi değiştirmek, şehir adıyla aramaya geri döner.",
    coordinatePermission: "Vakitleri almak için bu kayıtlı koordinatlar AlAdhan’a gönderilir.",
    autoLocation: "Otomatik konum", autoLocationHint: "Anında kaydedilir ve vakitler yenilenir. Ağınızdan yaklaşık şehir belirlenir; kayıtlı konumu kullanmak için kapatın.",
    autoPermission: "Otomatik mod, genel IP adresinizden şehrinizi tahmin etmek için wttr.in kullanır; bulunan koordinatlar vakitler için AlAdhan’a gönderilir.",
    done: "Hatırlatma kapatıldı", dismiss: "Hatırlatmayı kapat", setup: "Salah’a hoş geldiniz", setupBody: "Başlamak için konumunuzu ve hesaplama yöntemini seçin.",
    notifications: "Masaüstü bildirimleri", sound: "Ses", motion: "Hafif animasyon", countdown: "Çubukta geri sayımı göster",
    city: "Şehir", country: "Ülke", method: "Hesaplama yöntemi", school: "İkindi hesabı", language: "Dil",
    save: "Kaydet ve vakitleri getir", back: "Geri", refresh: "Yenile", preview: "Hatırlatmaları önizle", stop: "Sesi durdur",
    beforeWindow: "Namazdan önceki dakika", afterWindow: "Namazdan sonraki dakika", normal: "Hatırlatmalar arasında",
    permission: "Vakitler alınırken seçtiğiniz şehir ve ülke AlAdhan’a gönderilir. Hava durumu konumunuz ayrıdır.",
    source: "AlAdhan hesabı", local: "Yerel vakit çizelgesi", expired: "Bugünün vakitleri mevcut değil. Yenileyin veya çizelgeyi güncelleyin.",
    hint: "Hatırlatmayı kapatmak için camiye tıklayın. Sağ tık paneli açar; orta tık vakitleri yeniler.",
    acknowledgeOpen: "Tıklama paneli de açsın", soundFile: "Ses dosyası (tam yol)", filePath: "Vakit çizelgesi JSON dosyası (tam yol)",
    provider: "Vakit kaynağı", importSave: "Kaydet ve çizelgeyi yükle", ring: "Sarı: imsak / öğle öncesi\nKırmızı: ikindi / akşam / yatsı öncesi\nYeşil: vakit girdi", previewLabel: "Önizleme — gerçek vakit bildirimi değil"},
  ar: {next: "الصلاة القادمة", after: "حان وقت", before: "اقترب وقت", settings: "الإعدادات", today: "اليوم",
    countdownHint:"يُحفظ فوراً. قبل الصلاة: الوقت المتبقي للصلاة. بعدها: الوقت المتبقي للتذكير الأخضر. يختفي عند إغلاق التذكير.", countdownWindow:"إظهار العد التنازلي", countdownBoth:"قبل الصلاة وبعدها", countdownBefore:"قبل الصلاة فقط", countdownAfter:"بعد الصلاة فقط", reminderEnds:"ينتهي التذكير خلال",
    qiblaUndefined:"لا يمكن تحديد اتجاه وحيد للقبلة في هذا الموقع.",
    qibla:"اتجاه القبلة",trueNorth:"مع عقارب الساعة من الشمال الحقيقي",northShort:"ش",showQibla:"إظهار القبلة على الأرض",showQiblaHint:"يُحفظ فوراً. خط متقطع خفيف ينتهي عند مكة إن كانت مرئية، وإلا يتلاشى عند الأفق. يبقى الشمال في الأعلى.",qiblaUnavailable:"الاتجاه غير متاح. احفظ موقعاً بإحداثيات لحسابه.",
    displayMode: "عرض اللوحة", earth: "ساعة الأرض", classic: "الجدول الكلاسيكي", guidanceProfile: "إرشادات الصلاة", diyanetGuidance: "ديانت · حدود تقريبية", guidanceOff: "إيقاف",
    coordinates: "الإحداثيات المحفوظة", coordinatesHint: "تعديل المدينة أو الدولة يعيد البحث باسم المدينة.",
    coordinatePermission: "تُرسل هذه الإحداثيات المحفوظة إلى AlAdhan لجلب مواقيت الصلاة.",
    autoLocation: "الموقع التلقائي", autoLocationHint: "يُحفظ فوراً ويحدّث المواقيت. يقدّر المدينة من شبكتك؛ أوقفه لاستخدام موقعك اليدوي المحفوظ.",
    autoPermission: "يستخدم الوضع التلقائي wttr.in لتقدير مدينتك من عنوان IP العام، ثم يرسل الإحداثيات إلى AlAdhan لجلب المواقيت.",
    done: "تم إغلاق التذكير", dismiss: "إغلاق التذكير", setup: "مرحباً بك في صلاح", setupBody: "اختر موقعك وطريقة حساب مواقيت الصلاة للبدء.",
    notifications: "إشعارات سطح المكتب", sound: "الصوت", motion: "حركة هادئة", countdown: "إظهار العد التنازلي",
    city: "المدينة", country: "الدولة", method: "طريقة الحساب", school: "حساب العصر", language: "اللغة",
    save: "حفظ وجلب المواقيت", back: "رجوع", refresh: "تحديث", preview: "معاينة التذكيرات", stop: "إيقاف الصوت",
    beforeWindow: "دقائق قبل الصلاة", afterWindow: "دقائق بعد الصلاة", normal: "بين التذكيرات",
    permission: "يُرسل اسم المدينة والدولة المختارين إلى AlAdhan لجلب المواقيت. موقع الطقس مستقل.",
    source: "حساب AlAdhan", local: "جدول محلي", expired: "مواقيت اليوم غير متاحة. حدّث الجدول.",
    hint: "انقر المسجد لإغلاق التذكير الحالي. الزر الأيمن يفتح اللوحة والأوسط يحدّث المواقيت.",
    acknowledgeOpen: "النقر يفتح اللوحة أيضاً", soundFile: "ملف صوتي (مسار كامل)", filePath: "ملف جدول JSON (مسار كامل)",
    provider: "مصدر المواقيت", importSave: "حفظ وتحميل الجدول", ring: "أصفر: قبل الفجر / الظهر\nأحمر: قبل العصر / المغرب / العشاء\nأخضر: حان الوقت", previewLabel: "معاينة — ليس تنبيهاً لوقت الصلاة"}
}
function text(key, language) { return (messages[language] || messages.en)[key] || messages.en[key] || key }

var methods = [
  {value:"3",label:"Muslim World League"}, {value:"2",label:"ISNA — North America"},
  {value:"5",label:"Egyptian General Authority"}, {value:"4",label:"Umm Al-Qura — Makkah"},
  {value:"1",label:"University of Islamic Sciences — Karachi"}, {value:"7",label:"University of Tehran"},
  {value:"0",label:"Shia Ithna-Ashari — Qum"}, {value:"8",label:"Gulf Region"},
  {value:"9",label:"Kuwait"}, {value:"10",label:"Qatar"}, {value:"11",label:"Singapore"},
  {value:"12",label:"France"}, {value:"13",label:"Turkey / Diyanet (experimental calculation)"},
  {value:"14",label:"Russia"}, {value:"15",label:"Moonsighting Committee"},
  {value:"16",label:"Dubai (experimental)"}, {value:"17",label:"JAKIM — Malaysia"},
  {value:"18",label:"Tunisia"}, {value:"19",label:"Algeria"}, {value:"20",label:"KEMENAG — Indonesia"},
  {value:"21",label:"Morocco"}, {value:"22",label:"Lisbon"}, {value:"23",label:"Jordan"}
]
